//------------------------------------------------------------------------
// Copyright(c) 2024 wararyo.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SpeakerDelay.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SpeakerDelay VST3 (64Bit)"
#else
#define stringFileDescription	"SpeakerDelay VST3"
#endif
#define stringCompanyName		"wararyo\0"
#define stringLegalCopyright	"Copyright(c) 2024 wararyo."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
